name: Run Synthetic tests using the test public IDs
jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v0.24.0
        with:
          api_key: ${{env.DATADOG_API_KEY}}
          app_key: ${{env.DATADOG_APP_KEY}}
          public_ids: 'ebn-akz-9be'
